language: android

android:
  components:
  - build-tools-28.0.3
  - android-26
  licenses:
  - android-sdk-license-.+

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew clean build
  - ./gradlew test